name: Discord Notifications

on:
  pull_request: # pr - opened, reopened 이벤트 발생 시 discord 알림
    types: [opened, reopened]
    
jobs:
  discordNotification:
    runs-on: ubuntu-latest

    steps:
    - name: Discord Github Notification
      uses: Aleph-Kim/discord-github-notification@v1.2.1
      with:
        discord-webhook-url: ${{ secrets.CLOUDBOT_WEBHOOK }} # secret key에 저장한 discord webhook url
        language: "korean" # 필수 X
        custom: true # 필수 X